site_name: Lime API

plugins:
  - search

theme:
  highlightjs: true
  name: material
  font:
    code: Noto Sans
  palette:
    scheme: slate
    primary: light green
    accent: lime
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - News: news.md
  - API:
    - Runtime: ./api/runtime.md
    - Modules:
      - Lime: ./api/modules/lime.md
      - Input: ./api/modules/input.md
      - GUI: ./api/modules/gui.md
      - World: ./api/modules/world.md
      - Sound: ./api/modules/sound.md
      - Network:
        - NetworkClient: ./api/modules/networkclient.md
        - NetworkServer: ./api/modules/networkserver.md
    - Classes:
      - 2D:
        - Image2D: ./api/classes/2d/image2d.md
        - Text2D: ./api/classes/2d/text2d.md
        - EditBox: ./api/classes/2d/editbox.md
      - 3D:
        - Physics:
          - Coming Soon: 404.md
        - Camera: ./api/classes/3d/camera.md
        - Mesh: ./api/classes/3d/mesh.md
        - MeshBuffer: ./api/classes/3d/meshbuffer.md
        - Material: ./api/classes/3d/material.md
        - Empty: ./api/classes/3d/empty.md
        - Hitbox: ./api/classes/3d/hitbox.md
        - Billboard: ./api/classes/3d/billboard.md
        - Text3D: ./api/classes/3d/text3d.md
        - Water: ./api/classes/3d/water.md
        - Light: ./api/classes/3d/light.md
        - LegacyLight: ./api/classes/3d/legacylight.md
        - ParticleSystem: ./api/classes/3d/particlesystem.md
        - Trail: ./api/classes/3d/trail.md
      - Vector2D: ./api/classes/vector2d.md
      - Vector3D: ./api/classes/vector3d.md
      - Vector4D: ./api/classes/vector4d.md
      - Texture: ./api/classes/texture.md
      - Packet: ./api/classes/packet.md
    - Structs: ./api/structs.md
  - Examples:
    - 01 Hello World: example-01.md

repo_url: https://github.com/darttheg/Lime
repo_name: Lime

extra:
  alternate_404: true

use_directory_urls: false